export const elements = {
  //assets
  search: document.querySelector('.search'),
  searchText: document.querySelector('#search'),
  search1: document.querySelector('.search1'),
  searchText1: document.querySelector('#search1'),
  loader: document.querySelector('.addLoader'),
  addError: document.querySelector('.addError'),
  main: document.querySelector('.yes'),
  like: document.querySelector('.noLike'),
  likeMovies: document.querySelector('.movies'),
  photo1: document.querySelector('.photo1'),
  photo2: document.querySelector('.photo2'),
  photo3: document.querySelector('.photo3'),
  photo4: document.querySelector('.photo4'),
  photo5: document.querySelector('.photo5'),
  photo6: document.querySelector('.photo6'),
  photo7: document.querySelector('.photo7'),
  photo8: document.querySelector('.photo8'),
  photo9: document.querySelector('.photo9'),
  photo10: document.querySelector('.photo10'),
  photo11: document.querySelector('.photo11'),
  photo12: document.querySelector('.photo12'),
  photo13: document.querySelector('.photo13'),
  photo14: document.querySelector('.photo14'),
  photo15: document.querySelector('.photo15'),
};
